
[project]
authors = [
    {name = "Jim Barrett", email = "jimbarrett27@gmail.com"},
    {name = "Marcus Näslund", email = "naslundx@gmail.com"},
]
license = {text = "GPLv3"}
requires-python = "<4.0,>=3.9"
dependencies = [
    "pillow<11.0.0,>=10.4.0",
]
name = "wrdcld"
version = "0.2.0"
description = "A predictable, interpretable wordcloud library"
readme = "README.md"

[dependency-groups]
dev = [
    "black<25.0.0,>=24.8.0",
    "pylint<4.0.0,>=3.2.6",
    "jupyter<2.0.0,>=1.0.0",
    "isort<6.0.0,>=5.13.2",
    "hypothesis<7.0.0,>=6.111.0",
    "mypy<2.0.0,>=1.11.1",
    "types-pillow<11.0.0.0,>=10.2.0.20240520",
]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.9"
disallow_untyped_defs = false
show_error_codes = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true
