name: Linting & Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]
    name: 'Ubuntu, python ${{ matrix.python-version }}'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync -p ${{ matrix.python-version }}

      - name: Linting
        run: |
          uv run isort wrdcld tests examples --check
          uv run black wrdcld tests examples --check
          uv run pylint wrdcld tests examples
          uv run mypy wrdcld

      - name: Tests
        run: |
          uv run python -m unittest discover tests/
